volumes:
  db:

x-environment: &default-env
  TZ: "Etc/UTC"


services:

  web:
    build: .
    profiles:
      - web
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "db"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped


  db:
    image: "postgres:17.5"
    profiles:
      - web
      - db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      <<: *default-env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped