# https://docs.astral.sh/ruff/settings/#target-version
target-version = "py313"


# Same as Black.
line-length = 120
indent-width = 4


cache-dir = "~/.cache/ruff"

# Exclude a variety of commonly ignored directories.
# https://docs.astral.sh/ruff/settings/#exclude
exclude = [
    ".cache",
    "ruff",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "static",
    ".env*",
    "migrations",  # django migrations
]

# Project Based:
extend-exclude = [
]


[format]

# Like Black, use double quotes for strings.
quote-style = "double"


# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"



[lint]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []


# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"


# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
#select = ["E4", "E7", "E9", "F"]
select = [
    # # pycodestyle
    "E",

    # # Pyflakes
    "F",

    # # pyupgrade
    # "UP",

    # # flake8-bugbear
    # "B",

    # # flake8-simplify
    # "SIM",

    # # isort
    # "I",
]

# TODO: fresh config, in case of any issues don't forget to check:
# - conflicting rules: https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules

ignore = [

    # <<< ------------------------------------------- Pyflakes (`F`) -------------------------------------------- <<<
    #                                https://docs.astral.sh/ruff/rules/#pyflakes-f
    # <<< ------------------------------------------------------------------------------------------------------- <<<
    "F401",  # https://docs.astral.sh/ruff/rules/unused-import/ - Module imported but unused
    # ---------------------------------------------------------------------------------------------------------------
    "F841",  # https://docs.astral.sh/ruff/rules/unused-variable/ - Local variable name assigned to but never used
    # ---------------------------------------------------------------------------------------------------------------
    "F811", # TODO: temporary untill fixtures imports is fixed
    # ---------------------------------------------------------------------------------------------------------------
    # =========================================================================================================== >>>


    # <<< -------------------------------------- pycodestyle errors (`E`) --------------------------------------- <<<
    #                                 https://docs.astral.sh/ruff/rules/#error-e
    # <<< ------------------------------------------------------------------------------------------------------- <<<
    # "E203",  # https://docs.astral.sh/ruff/rules/whitespace-before-punctuation/ - Whitespace before ':'
    # ---------------------------------------------------------------------------------------------------------------
    # "E231",  # https://docs.astral.sh/ruff/rules/missing-whitespace/ - Missing whitespace after ',', ';', or ':'
    # ---------------------------------------------------------------------------------------------------------------
    "E401",  # https://docs.astral.sh/ruff/rules/multiple-imports-on-one-line/ - Multiple imports on one line
    # ---------------------------------------------------------------------------------------------------------------
    "E501",  # https://docs.astral.sh/ruff/rules/line-too-long/ - Line too long (defined by --max-line-length)  # todo: remove me
    # ---------------------------------------------------------------------------------------------------------------
    "E701",  # https://docs.astral.sh/ruff/rules/multiple-statements-on-one-line-colon/ - Multiple statements on one line (colon)
    # ---------------------------------------------------------------------------------------------------------------
    "E731",  # https://docs.astral.sh/ruff/rules/lambda-assignment/ - Do not assign a lambda expression, use a def
    # ---------------------------------------------------------------------------------------------------------------
    # "E704", # not working atm: https://github.com/PyCQA/pycodestyle/pull/957
    # ---------------------------------------------------------------------------------------------------------------
    # =========================================================================================================== >>>


    # <<< --------------------------------------- pycodestyle warnings (`W`) ------------------------------------ <<<
    #                                  https://docs.astral.sh/ruff/rules/#warning-w
    # <<< ------------------------------------------------------------------------------------------------------- <<<
    # "W291",  # https://docs.astral.sh/ruff/rules/trailing-whitespace/ - Trailing whitespace
    # ---------------------------------------------------------------------------------------------------------------
    # "W293",  # https://docs.astral.sh/ruff/rules/blank-line-with-whitespace/ - Blank line contains whitespace
    # ---------------------------------------------------------------------------------------------------------------
    # =========================================================================================================== >>>


    # <<< ---------------------------------------- flake8-print (`T20`) ----------------------------------------- <<<
    #                             https://docs.astral.sh/ruff/rules/#flake8-print-t20
    # <<< ------------------------------------------------------------------------------------------------------- <<<
    "T201",  # https://docs.astral.sh/ruff/rules/print/ - Checks for print statements
    # ---------------------------------------------------------------------------------------------------------------
    "T203",  # https://docs.astral.sh/ruff/rules/p-print/ - Checks for pprint statements
    # ---------------------------------------------------------------------------------------------------------------
    # =========================================================================================================== >>>


    # <<< -------------------------------------- flake8-pytest-style (PT) --------------------------------------- <<<
    #                           https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
    # <<< ------------------------------------------------------------------------------------------------------- <<<
    "PT001",  # https://docs.astral.sh/ruff/rules/pytest-fixture-incorrect-parentheses-style/ - Wrong test function name
    # ---------------------------------------------------------------------------------------------------------------
    # =========================================================================================================== >>>


]

#[lint.flake8-quotes]
#docstring-quotes = "double"

