# Generated by Django 5.2.4 on 2025-08-04 23:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0E-18'), max_digits=78, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['label'], name='idx-Wallet:label'), models.Index(fields=['balance'], name='idx-Wallet:balance'), models.Index(fields=['label', 'balance'], name='idx-Wallet:label-balance')],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=78)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['amount'], name='idx-Transaction:amount'), models.Index(fields=['wallet_id', 'amount'], name='idx-Transaction:wallet-amount'), models.Index(fields=['wallet_id', 'id'], name='idx-Transaction:wallet-id')],
            },
        ),
    ]
